/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/v1/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["MainController_health_v1"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/stats": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Platform-wide KPI statistics (super admin only) */
		get: operations["AdminController_getStats_v1"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/users": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all users with admin roles across all tenants (super admin only) */
		get: operations["AdminController_listUsers_v1"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/users/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Toggle super-admin status for a user (super admin only) */
		patch: operations["AdminController_toggleSuperAdmin_v1"];
		trace?: never;
	};
	"/api/v1/auth/session": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Exchange a Firebase ID token for an application session
		 * @description Verifies the Firebase ID token, upserts the global User row, snapshots every tenant membership into custom claims, and returns the populated session.
		 */
		post: operations["AuthController_createSession_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Return the decoded Firebase token for the current request
		 * @description Shape mirrors the normalised AuthUser, including the tenantMemberships claim keyed by tenant slug.
		 */
		get: operations["AuthController_me_v1"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List all churches with per-tenant aggregates (super admin only) */
		get: operations["TenantController_list_v1"];
		put?: never;
		/** Create a new church (super admin only) */
		post: operations["TenantController_create_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/slug-suggestion": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Suggest a slug from a tenant name */
		get: operations["TenantController_suggestSlug_v1"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a church by id or slug
		 * @description Caller must be a member of the tenant, or a super-admin. Accepts UUID or slug in :tenantId.
		 */
		get: operations["TenantController_getById_v1"];
		put?: never;
		post?: never;
		/** Soft-delete a church (super admin only) */
		delete: operations["TenantController_delete_v1"];
		options?: never;
		head?: never;
		/** Update a church (admin or super-admin) */
		patch: operations["TenantController_update_v1"];
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/slug": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Rename a church slug (super admin only) */
		patch: operations["TenantController_rename_v1"];
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/restore": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Restore a soft-deleted church (super admin only) */
		post: operations["TenantController_restore_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/members": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List members (admin only) */
		get: operations["MemberController_list_v1"];
		put?: never;
		/** Create a temp member (admin only) */
		post: operations["MemberController_create_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/members/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get the current user’s member row in this tenant
		 * @description Any member (USER or ADMIN) can call this for themselves. Super-admins with no Member row in the tenant get 404.
		 */
		get: operations["MemberController_me_v1"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Update the current user’s own member profile
		 * @description Members can update their own first/last name, phone, address. Email is bound to SSO and not editable here. Role + status are admin-only.
		 */
		patch: operations["MemberController_updateMe_v1"];
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/members/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a member by id (admin only) */
		get: operations["MemberController_getById_v1"];
		put?: never;
		post?: never;
		/** Soft-delete a member */
		delete: operations["MemberController_delete_v1"];
		options?: never;
		head?: never;
		/** Update a member */
		patch: operations["MemberController_update_v1"];
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/members/{id}/merge-preview": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Preview a merge: shows what will move from drop → keep without mutating
		 * @description Use this to render a confirmation modal. Pass the candidate to drop via ?dropId=. Returns transaction/pledge counts and the field-copy plan.
		 */
		get: operations["MemberController_mergePreview_v1"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/members/{id}/merge": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Merge another member into this one
		 * @description Reassigns transactions and pledges from the drop member to this one, copies any contact fields the keeper is missing, then soft-deletes the drop member.
		 */
		post: operations["MemberController_merge_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/campaigns": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List campaigns for a tenant */
		get: operations["CampaignController_list_v1"];
		put?: never;
		/** Create a campaign */
		post: operations["CampaignController_create_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/campaigns/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a campaign with its items */
		get: operations["CampaignController_getById_v1"];
		put?: never;
		post?: never;
		/** Soft-delete a campaign */
		delete: operations["CampaignController_delete_v1"];
		options?: never;
		head?: never;
		/** Update a campaign */
		patch: operations["CampaignController_update_v1"];
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/campaigns/{id}/progress": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Campaign progress (goal / pledged / raised, with per-item breakdown) */
		get: operations["CampaignController_progress_v1"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/campaigns/{id}/restore": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Restore a soft-deleted campaign */
		post: operations["CampaignController_restore_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/campaigns/{id}/items": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Add a breakdown item to a campaign */
		post: operations["CampaignController_addItem_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/campaigns/{id}/items/{itemId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Soft-delete a campaign item */
		delete: operations["CampaignController_deleteItem_v1"];
		options?: never;
		head?: never;
		/** Update a campaign item */
		patch: operations["CampaignController_updateItem_v1"];
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/pledges": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List pledges
		 * @description Members see only their own; admins and super-admins see all within the tenant.
		 */
		get: operations["PledgeController_list_v1"];
		put?: never;
		/**
		 * Create a pledge
		 * @description Members can pledge on their own behalf (memberId is ignored and forced to self). Admins can pledge on behalf of any member in the tenant.
		 */
		post: operations["PledgeController_create_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/pledges/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a pledge by id */
		get: operations["PledgeController_getById_v1"];
		put?: never;
		post?: never;
		/** Soft-delete a pledge (admin only) */
		delete: operations["PledgeController_delete_v1"];
		options?: never;
		head?: never;
		/** Update a pledge */
		patch: operations["PledgeController_update_v1"];
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/transactions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List transactions
		 * @description Members see only their own; admins and super-admins see all within the tenant.
		 */
		get: operations["TransactionController_list_v1"];
		put?: never;
		/** Record an incoming transaction */
		post: operations["TransactionController_create_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/transactions/summary": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Aggregate transaction totals for the admin dashboard
		 * @description Returns totals-by-type and a monthly trend for the last 12 months. Restricted to admins.
		 */
		get: operations["TransactionController_summary_v1"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/transactions/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a transaction by id */
		get: operations["TransactionController_getById_v1"];
		put?: never;
		post?: never;
		/** Soft-delete a transaction */
		delete: operations["TransactionController_delete_v1"];
		options?: never;
		head?: never;
		/** Update a transaction */
		patch: operations["TransactionController_update_v1"];
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/invitations": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List pending invitations for a tenant (admin only) */
		get: operations["InvitationController_list_v1"];
		put?: never;
		/** Issue an invitation to a member or admin (admin only) */
		post: operations["InvitationController_issue_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/invitations/lookup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Look up an invitation by token (public) */
		get: operations["InvitationController_lookup_v1"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/invitations/accept": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Accept an invitation using the token emailed to the invitee */
		post: operations["InvitationController_accept_v1"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tenants/{tenantId}/invitations/{invitationId}/cancel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Cancel a pending invitation (admin only) */
		patch: operations["InvitationController_cancel_v1"];
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		PlatformStatsDto: {
			/**
			 * @description Total non-deleted tenants
			 * @example 0
			 */
			totalTenants: number;
			/**
			 * @description Tenants created in the current calendar month
			 * @example 0
			 */
			createdThisMonth: number;
			/**
			 * @description Total non-deleted super-admin users
			 * @example 0
			 */
			superAdmins: number;
			/**
			 * @description Total members with ADMIN role across all tenants
			 * @example 0
			 */
			totalAdmins: number;
			/**
			 * @description Total non-deleted members across all tenants
			 * @example 0
			 */
			totalMembers: number;
			/**
			 * @description New members in the current calendar month
			 * @example 0
			 */
			newMembersThisMonth: number;
			/**
			 * @description Gift transactions in the last 30 days
			 * @example 0
			 */
			giftsLast30dCount: number;
			/**
			 * @description Total gift amount in the last 30 days
			 * @example 100.5
			 */
			giftsLast30dTotal: number;
		};
		AdminUserMembershipDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			tenantId: string;
			/** @example grace-community */
			tenantSlug: string;
			/** @example Grace Community Church */
			tenantName: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			memberId: string;
			/**
			 * @example ADMIN
			 * @enum {string}
			 */
			role: "ADMIN" | "USER";
		};
		AdminUserDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/** @example john.doe@example.com */
			email: string;
			/** @example John Doe */
			displayName: string;
			/** @example https://example.com/image.png */
			photoUrl?: Record<string, never> | null;
			/** @example true */
			isSuperAdmin: boolean;
			memberships: components["schemas"]["AdminUserMembershipDto"][];
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
		};
		AdminUserListResponseDto: {
			items: components["schemas"]["AdminUserDto"][];
			/** @example 0 */
			total: number;
		};
		ToggleSuperAdminRequestDto: {
			/** @example true */
			isSuperAdmin: boolean;
		};
		ExchangeTokenRequestDto: {
			/**
			 * @description Firebase ID token obtained from the client SDK after Google sign-in
			 * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.payload.signature
			 */
			idToken: string;
		};
		UserDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/** @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9 */
			firebaseUid: string;
			/** @example john.doe@example.com */
			email: string;
			/** @example John Doe */
			displayName: string;
			/** @example https://example.com/image.png */
			photoUrl?: Record<string, never> | null;
			/** @example true */
			isSuperAdmin: boolean;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
		};
		TenantMembershipDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			tenantId: string;
			/**
			 * @description URL-safe tenant slug — used in frontend paths and as the key for tenantMemberships claims.
			 * @example grace-community
			 */
			slug: string;
			/** @example Grace Community Church */
			name: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			memberId: string;
			/**
			 * @example ADMIN
			 * @enum {string}
			 */
			role: "ADMIN" | "USER";
		};
		SessionResponseDto: {
			user: components["schemas"]["UserDto"];
			tenantMemberships: components["schemas"]["TenantMembershipDto"][];
			/** @example false */
			isSuperAdmin: boolean;
		};
		AuthMeResponseDto: {
			/** @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9 */
			firebaseUid: string;
			/** @example john.doe@example.com */
			email: string;
			/** @example John Doe */
			displayName?: string;
			/** @example https://example.com/image.png */
			picture?: string;
			/** @example false */
			isSuperAdmin: boolean;
			/**
			 * @description Map of tenant-slug → { memberId, role }. Keys are slugs so frontend URLs can be used as-is.
			 * @example {
			 *       "grace-community": {
			 *         "memberId": "b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11",
			 *         "role": "ADMIN"
			 *       }
			 *     }
			 */
			tenantMemberships: {
				[key: string]: {
					/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
					memberId?: string;
					/** @enum {unknown} */
					role?: "ADMIN" | "USER";
				};
			};
		};
		CreateTenantRequestDto: {
			/**
			 * @description URL-safe identifier. Lowercase alphanumerics and hyphens only, 3–64 chars.
			 * @example grace-community
			 */
			slug: string;
			/** @example Grace Community Church */
			name: string;
			/** @example 123 Main St, Anytown, CA */
			address?: string;
			/** @example +15555550123 */
			phone?: string;
			/** @example john.doe@example.com */
			email?: string;
			/** @example https://example.com/image.png */
			logoUrl?: string;
			/**
			 * @example [
			 *       "building_fund",
			 *       "youth_ministry"
			 *     ]
			 */
			customTransactionTypes?: string[];
		};
		TenantResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/**
			 * @description URL-safe unique identifier. Used in frontend paths like /[slug]/admin/* and as a key in tenantMemberships custom claims.
			 * @example grace-community
			 */
			slug: string;
			/**
			 * @description Church name
			 * @example Grace Community Church
			 */
			name: string;
			/** @example 123 Main St, Anytown, CA */
			address?: Record<string, never> | null;
			/** @example +15555550123 */
			phone?: Record<string, never> | null;
			/** @example john.doe@example.com */
			email?: Record<string, never> | null;
			/** @example https://example.com/image.png */
			logoUrl?: Record<string, never> | null;
			/**
			 * @description Tenant-defined custom transaction types
			 * @example [
			 *       "building_fund",
			 *       "youth_ministry"
			 *     ]
			 */
			customTransactionTypes: string[];
			/**
			 * @description Firebase UID of creator
			 * @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9
			 */
			createdBy: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
			/** @example 2026-01-01T00:00:00.000Z */
			deletedAt?: Record<string, never> | null;
		};
		TenantAdminPreviewDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			memberId: string;
			/** @example John Doe */
			displayName: string;
			/** @example https://example.com/image.png */
			photoUrl?: Record<string, never> | null;
		};
		TenantListItemDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/**
			 * @description URL-safe unique identifier. Used in frontend paths like /[slug]/admin/* and as a key in tenantMemberships custom claims.
			 * @example grace-community
			 */
			slug: string;
			/**
			 * @description Church name
			 * @example Grace Community Church
			 */
			name: string;
			/** @example 123 Main St, Anytown, CA */
			address?: Record<string, never> | null;
			/** @example +15555550123 */
			phone?: Record<string, never> | null;
			/** @example john.doe@example.com */
			email?: Record<string, never> | null;
			/** @example https://example.com/image.png */
			logoUrl?: Record<string, never> | null;
			/**
			 * @description Tenant-defined custom transaction types
			 * @example [
			 *       "building_fund",
			 *       "youth_ministry"
			 *     ]
			 */
			customTransactionTypes: string[];
			/**
			 * @description Firebase UID of creator
			 * @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9
			 */
			createdBy: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
			/** @example 2026-01-01T00:00:00.000Z */
			deletedAt?: Record<string, never> | null;
			/**
			 * @description Number of members with ADMIN role
			 * @example 0
			 */
			adminCount: number;
			/**
			 * @description Total non-deleted members
			 * @example 0
			 */
			memberCount: number;
			/** @description Up to 3 admin previews for avatar stack */
			adminsPreview: components["schemas"]["TenantAdminPreviewDto"][];
			/**
			 * @description Gift transactions in the current calendar month
			 * @example 0
			 */
			giftsMtdCount: number;
			/**
			 * @description Total gift amount in the current calendar month
			 * @example 100.5
			 */
			giftsMtdTotal: number;
		};
		TenantListResponseDto: {
			items: components["schemas"]["TenantListItemDto"][];
		};
		UpdateTenantRequestDto: {
			/** @example Grace Community Church */
			name?: string;
			/** @example 123 Main St, Anytown, CA */
			address?: string;
			/** @example +15555550123 */
			phone?: string;
			/** @example john.doe@example.com */
			email?: string;
			/** @example https://example.com/image.png */
			logoUrl?: string;
			/**
			 * @example [
			 *       "building_fund",
			 *       "youth_ministry"
			 *     ]
			 */
			customTransactionTypes?: string[];
		};
		RenameTenantRequestDto: {
			/** @example grace-community */
			slug: string;
		};
		DeleteResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
		};
		CreateMemberRequestDto: {
			/** @example John */
			firstName: string;
			/** @example Doe */
			lastName: string;
			/** @example john.doe@example.com */
			email?: string;
			/** @example +15555550123 */
			phone?: string;
			/** @example 123 Main St, Anytown, CA */
			address?: string;
			/**
			 * @default USER
			 * @enum {string}
			 */
			role: "ADMIN" | "USER";
		};
		MemberResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			tenantId: string;
			/**
			 * @description Linked User.id if the member has a registered account; null for temp members
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			userId?: Record<string, never> | null;
			/** @example John */
			firstName: string;
			/** @example Doe */
			lastName: string;
			/** @example john.doe@example.com */
			email?: Record<string, never> | null;
			/** @example +15555550123 */
			phone?: Record<string, never> | null;
			/** @example 123 Main St, Anytown, CA */
			address?: Record<string, never> | null;
			/**
			 * @example USER
			 * @enum {string}
			 */
			role: "ADMIN" | "USER";
			/**
			 * @example ACTIVE
			 * @enum {string}
			 */
			status: "ACTIVE" | "INACTIVE";
			/** @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9 */
			createdBy: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
		};
		MetaDto: {
			/**
			 * @description Number of items skipped
			 * @example 0
			 */
			offset: number;
			/**
			 * @description Page size
			 * @example 50
			 */
			limit: number;
			/**
			 * @description Total items matching the query
			 * @example 128
			 */
			total: number;
		};
		MemberListResponseDto: {
			items: components["schemas"]["MemberResponseDto"][];
			meta: components["schemas"]["MetaDto"];
		};
		UpdateMyMembershipRequestDto: {
			/** @example John */
			firstName?: string;
			/** @example Doe */
			lastName?: string;
			/** @example +15555550123 */
			phone?: string;
			/** @example 123 Main St, Anytown, CA */
			address?: string;
		};
		UpdateMemberRequestDto: {
			/** @example John */
			firstName?: string;
			/** @example Doe */
			lastName?: string;
			/** @example john.doe@example.com */
			email?: string;
			/** @example +15555550123 */
			phone?: string;
			/** @example 123 Main St, Anytown, CA */
			address?: string;
			/**
			 * @default USER
			 * @enum {string}
			 */
			role: "ADMIN" | "USER";
			/** @enum {string} */
			status?: "ACTIVE" | "INACTIVE";
		};
		MergeMembersPreviewResponseDto: {
			keep: components["schemas"]["MemberResponseDto"];
			drop: components["schemas"]["MemberResponseDto"];
			/** @example 12 */
			transactionsToMove: number;
			/** @example 3 */
			pledgesToMove: number;
			/**
			 * @example [
			 *       "email",
			 *       "userId"
			 *     ]
			 */
			fieldsCopiedFromDrop: ("email" | "phone" | "address" | "userId")[];
		};
		MergeMembersRequestDto: {
			/**
			 * @description Id of the member that will be removed; its data is moved into the keeper.
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			dropId: string;
		};
		MergeMembersResponseDto: {
			keep: components["schemas"]["MemberResponseDto"];
			drop: components["schemas"]["MemberResponseDto"];
			/** @example 12 */
			transactionsToMove: number;
			/** @example 3 */
			pledgesToMove: number;
			/**
			 * @example [
			 *       "email",
			 *       "userId"
			 *     ]
			 */
			fieldsCopiedFromDrop: ("email" | "phone" | "address" | "userId")[];
			merged: components["schemas"]["MemberResponseDto"];
		};
		CreateCampaignRequestDto: {
			/** @example New Sanctuary Building Fund */
			title: string;
			/** @example Raising funds for the new sanctuary construction, phased through 2027. */
			description?: string;
			/**
			 * Format: date-time
			 * @description Omit for open-ended campaigns
			 * @example 2026-01-01T00:00:00.000Z
			 */
			deadline?: string;
			/** @enum {string} */
			status?: "DRAFT" | "ACTIVE" | "COMPLETED" | "CANCELLED";
		};
		CampaignResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			tenantId: string;
			/** @example New Sanctuary Building Fund */
			title: string;
			/** @example Raising funds for the new sanctuary construction, phased through 2027. */
			description?: Record<string, never> | null;
			/**
			 * @description Null = open-ended campaign (no hard deadline)
			 * @example 2026-01-01T00:00:00.000Z
			 */
			deadline?: Record<string, never> | null;
			/**
			 * @example ACTIVE
			 * @enum {string}
			 */
			status: "DRAFT" | "ACTIVE" | "COMPLETED" | "CANCELLED";
			/** @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9 */
			createdBy: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
		};
		CampaignListResponseDto: {
			items: components["schemas"]["CampaignResponseDto"][];
			meta: components["schemas"]["MetaDto"];
		};
		CampaignItemResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			tenantId: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			campaignId: string;
			/** @example Roofing */
			title: string;
			/** @example string */
			description?: Record<string, never> | null;
			/**
			 * @description Target raise amount for this item
			 * @example 100.5
			 */
			targetAmount: number;
			/**
			 * @description Null = inherit campaign deadline
			 * @example 2026-01-01T00:00:00.000Z
			 */
			deadline?: Record<string, never> | null;
			/** @example 0 */
			sortOrder: number;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
		};
		CampaignWithItemsResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			tenantId: string;
			/** @example New Sanctuary Building Fund */
			title: string;
			/** @example Raising funds for the new sanctuary construction, phased through 2027. */
			description?: Record<string, never> | null;
			/**
			 * @description Null = open-ended campaign (no hard deadline)
			 * @example 2026-01-01T00:00:00.000Z
			 */
			deadline?: Record<string, never> | null;
			/**
			 * @example ACTIVE
			 * @enum {string}
			 */
			status: "DRAFT" | "ACTIVE" | "COMPLETED" | "CANCELLED";
			/** @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9 */
			createdBy: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
			items: components["schemas"]["CampaignItemResponseDto"][];
		};
		CampaignItemProgressDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			itemId: string;
			/** @example Roofing */
			title: string;
			/** @example 100.5 */
			targetAmount: number;
			/**
			 * @description Sum of pledges against this item
			 * @example 100.5
			 */
			pledgedAmount: number;
			/**
			 * @description Sum of transactions attributed to this item
			 * @example 100.5
			 */
			raisedAmount: number;
			/** @example 0 */
			pledgeCount: number;
		};
		CampaignProgressResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			campaignId: string;
			/**
			 * @description Goal = sum of items.targetAmount
			 * @example 100.5
			 */
			goalAmount: number;
			/**
			 * @description Sum of pledges (items + unscoped campaign pledges)
			 * @example 100.5
			 */
			pledgedAmount: number;
			/**
			 * @description Sum of transactions attributed to this campaign
			 * @example 100.5
			 */
			raisedAmount: number;
			/**
			 * @description Total active pledges
			 * @example 0
			 */
			pledgeCount: number;
			items: components["schemas"]["CampaignItemProgressDto"][];
		};
		UpdateCampaignRequestDto: {
			/** @example New Sanctuary Building Fund */
			title?: string;
			/** @example Raising funds for the new sanctuary construction, phased through 2027. */
			description?: string;
			/**
			 * Format: date-time
			 * @description Omit for open-ended campaigns
			 * @example 2026-01-01T00:00:00.000Z
			 */
			deadline?: string;
			/** @enum {string} */
			status?: "DRAFT" | "ACTIVE" | "COMPLETED" | "CANCELLED";
		};
		CreateCampaignItemRequestDto: {
			/** @example Roofing */
			title: string;
			/** @example Raising funds for the new sanctuary construction, phased through 2027. */
			description?: string;
			/** @example 100.5 */
			targetAmount: number;
			/**
			 * Format: date-time
			 * @description Defaults to the campaign deadline when omitted
			 * @example 2026-01-01T00:00:00.000Z
			 */
			deadline?: string;
			/** @example 0 */
			sortOrder?: number;
		};
		UpdateCampaignItemRequestDto: {
			/** @example Roofing */
			title?: string;
			/** @example Raising funds for the new sanctuary construction, phased through 2027. */
			description?: string;
			/** @example 100.5 */
			targetAmount?: number;
			/**
			 * Format: date-time
			 * @description Defaults to the campaign deadline when omitted
			 * @example 2026-01-01T00:00:00.000Z
			 */
			deadline?: string;
			/** @example 0 */
			sortOrder?: number;
		};
		CreatePledgeRequestDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			campaignId: string;
			/**
			 * @description Omit to pledge against the overall campaign, not a specific item
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			campaignItemId?: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			memberId: string;
			/** @example 100.5 */
			pledgedAmount: number;
			/** @enum {string} */
			status?: "ACTIVE" | "FULFILLED" | "CANCELLED";
			/** @example string */
			note?: string;
		};
		PledgeResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			tenantId: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			campaignId: string;
			/**
			 * @description Null = pledge applies to overall campaign, not a specific item
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			campaignItemId?: Record<string, never> | null;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			memberId: string;
			/** @example 100.5 */
			pledgedAmount: number;
			/**
			 * @example ACTIVE
			 * @enum {string}
			 */
			status: "ACTIVE" | "FULFILLED" | "CANCELLED";
			/** @example string */
			note?: Record<string, never> | null;
			/** @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9 */
			createdBy: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
		};
		PledgeListMetaDto: {
			/**
			 * @description Number of items skipped
			 * @example 0
			 */
			offset: number;
			/**
			 * @description Page size
			 * @example 50
			 */
			limit: number;
			/**
			 * @description Total items matching the query
			 * @example 128
			 */
			total: number;
			/**
			 * @description Sum of pledgedAmount in the current filter
			 * @example 100.5
			 */
			sum: number;
		};
		PledgeListResponseDto: {
			items: components["schemas"]["PledgeResponseDto"][];
			meta: components["schemas"]["PledgeListMetaDto"];
		};
		UpdatePledgeRequestDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			campaignId?: string;
			/**
			 * @description Omit to pledge against the overall campaign, not a specific item
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			campaignItemId?: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			memberId?: string;
			/** @example 100.5 */
			pledgedAmount?: number;
			/** @enum {string} */
			status?: "ACTIVE" | "FULFILLED" | "CANCELLED";
			/** @example string */
			note?: string;
		};
		CreateTransactionRequestDto: {
			/**
			 * @example TITHE
			 * @enum {string}
			 */
			type:
				| "TITHE"
				| "OFFERING"
				| "MISSION_GIVING"
				| "FIRST_FRUIT"
				| "COMMITMENT"
				| "DONATION"
				| "OTHER";
			/** @example 100.5 */
			amount: number;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			date: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			memberId?: string;
			/**
			 * @description Campaign this gift is attributed to
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			campaignId?: string;
			/**
			 * @description Campaign item earmark. Must belong to campaignId when both are set.
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			campaignItemId?: string;
			/**
			 * @description Pledge this payment fulfills. When set, campaignId and campaignItemId must match the pledge.
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			pledgeId?: string;
			/** @example string */
			customType?: string;
			/** @example string */
			note?: string;
			/** @example CHK-000123 */
			referenceNumber?: string;
		};
		TransactionResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			tenantId: string;
			/**
			 * @description Member this transaction belongs to (null = anonymous/unlinked)
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			memberId?: Record<string, never> | null;
			/**
			 * @description Campaign this gift is attributed to (null = no campaign)
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			campaignId?: Record<string, never> | null;
			/**
			 * @description Campaign item this gift is earmarked to (null = general to campaign)
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			campaignItemId?: Record<string, never> | null;
			/**
			 * @description Pledge this payment fulfills (null = not against a specific pledge)
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			pledgeId?: Record<string, never> | null;
			/**
			 * @example TITHE
			 * @enum {string}
			 */
			type:
				| "TITHE"
				| "OFFERING"
				| "MISSION_GIVING"
				| "FIRST_FRUIT"
				| "COMMITMENT"
				| "DONATION"
				| "OTHER";
			/**
			 * @description Only set when type is OTHER and the tenant has defined custom types
			 * @example string
			 */
			customType?: Record<string, never> | null;
			/**
			 * @description Positive decimal (2 places)
			 * @example 100.5
			 */
			amount: number;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			date: string;
			/** @example string */
			note?: Record<string, never> | null;
			/** @example CHK-000123 */
			referenceNumber?: Record<string, never> | null;
			/** @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9 */
			createdBy: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
		};
		TransactionListMetaDto: {
			/**
			 * @description Number of items skipped
			 * @example 0
			 */
			offset: number;
			/**
			 * @description Page size
			 * @example 50
			 */
			limit: number;
			/**
			 * @description Total items matching the query
			 * @example 128
			 */
			total: number;
			/**
			 * @description Sum of amounts in the current filter
			 * @example 100.5
			 */
			sum: number;
		};
		TransactionListResponseDto: {
			items: components["schemas"]["TransactionResponseDto"][];
			meta: components["schemas"]["TransactionListMetaDto"];
		};
		TransactionSummaryByTypeDto: {
			/** @enum {string} */
			type:
				| "TITHE"
				| "OFFERING"
				| "MISSION_GIVING"
				| "FIRST_FRUIT"
				| "COMMITMENT"
				| "DONATION"
				| "OTHER";
			/** @example 100.5 */
			total: number;
			/** @example 12 */
			count: number;
		};
		TransactionSummaryByMonthDto: {
			/**
			 * @description YYYY-MM UTC bucket
			 * @example 2026-04
			 */
			month: string;
			/** @example 100.5 */
			total: number;
			/** @example 5 */
			count: number;
		};
		TransactionSummaryResponseDto: {
			/**
			 * @description Total across the entire window
			 * @example 100.5
			 */
			total: number;
			/**
			 * @description Number of transactions in the window
			 * @example 42
			 */
			count: number;
			byType: components["schemas"]["TransactionSummaryByTypeDto"][];
			byMonth: components["schemas"]["TransactionSummaryByMonthDto"][];
		};
		UpdateTransactionRequestDto: {
			/**
			 * @example TITHE
			 * @enum {string}
			 */
			type?:
				| "TITHE"
				| "OFFERING"
				| "MISSION_GIVING"
				| "FIRST_FRUIT"
				| "COMMITMENT"
				| "DONATION"
				| "OTHER";
			/** @example 100.5 */
			amount?: number;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			date?: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			memberId?: string;
			/**
			 * @description Campaign this gift is attributed to
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			campaignId?: string;
			/**
			 * @description Campaign item earmark. Must belong to campaignId when both are set.
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			campaignItemId?: string;
			/**
			 * @description Pledge this payment fulfills. When set, campaignId and campaignItemId must match the pledge.
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			pledgeId?: string;
			/** @example string */
			customType?: string;
			/** @example string */
			note?: string;
			/** @example CHK-000123 */
			referenceNumber?: string;
		};
		IssueInvitationRequestDto: {
			/** @example john.doe@example.com */
			email: string;
			/**
			 * @example USER
			 * @enum {string}
			 */
			role: "ADMIN" | "USER";
			/**
			 * @description Existing temp member to link to when this invitation is accepted
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			memberId?: string;
		};
		InvitationResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			tenantId: string;
			/** @example john.doe@example.com */
			email: string;
			/**
			 * @example USER
			 * @enum {string}
			 */
			role: "ADMIN" | "USER";
			/**
			 * @description Member this invitation links to on acceptance
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			memberId?: Record<string, never> | null;
			/**
			 * @example PENDING
			 * @enum {string}
			 */
			status: "PENDING" | "ACCEPTED" | "EXPIRED" | "CANCELLED";
			/** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.payload.signature */
			token: string;
			/** @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9 */
			invitedBy: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			expiresAt: string;
			/** @example 2026-01-01T00:00:00.000Z */
			acceptedAt?: Record<string, never> | null;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
		};
		InvitationListResponseDto: {
			items: components["schemas"]["InvitationResponseDto"][];
		};
		LookupInvitationResponseDto: {
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			id: string;
			/** @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11 */
			tenantId: string;
			/** @example john.doe@example.com */
			email: string;
			/**
			 * @example USER
			 * @enum {string}
			 */
			role: "ADMIN" | "USER";
			/**
			 * @description Member this invitation links to on acceptance
			 * @example b3b3a2c2-9c4d-4a12-8f15-7e0a1d9a2c11
			 */
			memberId?: Record<string, never> | null;
			/**
			 * @example PENDING
			 * @enum {string}
			 */
			status: "PENDING" | "ACCEPTED" | "EXPIRED" | "CANCELLED";
			/** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.payload.signature */
			token: string;
			/** @example xGqY3rtbiNa1z8VmOPqRsTuVwXy9 */
			invitedBy: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			expiresAt: string;
			/** @example 2026-01-01T00:00:00.000Z */
			acceptedAt?: Record<string, never> | null;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @example 2026-01-01T00:00:00.000Z
			 */
			updatedAt: string;
			/** @example Grace Community Church */
			tenantName: string;
			/** @example grace-community */
			tenantSlug: string;
			/** @example Pastor David Obi */
			inviterDisplayName?: Record<string, never> | null;
		};
		AcceptInvitationRequestDto: {
			/** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.payload.signature */
			token: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	MainController_health_v1: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AdminController_getStats_v1: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PlatformStatsDto"];
				};
			};
		};
	};
	AdminController_listUsers_v1: {
		parameters: {
			query?: {
				/** @description Filter by email or displayName (case-insensitive) */
				search?: string;
				/** @description Filter users who are members of this tenant */
				tenantId?: string;
				/** @description When true, return only super-admin users */
				superAdminOnly?: boolean;
				skip?: number;
				take?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminUserListResponseDto"];
				};
			};
		};
	};
	AdminController_toggleSuperAdmin_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description User UUID */
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ToggleSuperAdminRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminUserDto"];
				};
			};
		};
	};
	AuthController_createSession_v1: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ExchangeTokenRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionResponseDto"];
				};
			};
		};
	};
	AuthController_me_v1: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AuthMeResponseDto"];
				};
			};
		};
	};
	TenantController_list_v1: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TenantListResponseDto"];
				};
			};
		};
	};
	TenantController_create_v1: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateTenantRequestDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TenantResponseDto"];
				};
			};
		};
	};
	TenantController_suggestSlug_v1: {
		parameters: {
			query: {
				name: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						slug?: string;
					};
				};
			};
		};
	};
	TenantController_getById_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TenantResponseDto"];
				};
			};
		};
	};
	TenantController_delete_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeleteResponseDto"];
				};
			};
		};
	};
	TenantController_update_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateTenantRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TenantResponseDto"];
				};
			};
		};
	};
	TenantController_rename_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RenameTenantRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TenantResponseDto"];
				};
			};
		};
	};
	TenantController_restore_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID (slug not supported for soft-deleted rows) */
				tenantId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TenantResponseDto"];
				};
			};
		};
	};
	MemberController_list_v1: {
		parameters: {
			query?: {
				status?: "ACTIVE" | "INACTIVE";
				search?: string;
				offset?: number;
				limit?: number;
			};
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemberListResponseDto"];
				};
			};
		};
	};
	MemberController_create_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateMemberRequestDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemberResponseDto"];
				};
			};
		};
	};
	MemberController_me_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemberResponseDto"];
				};
			};
		};
	};
	MemberController_updateMe_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateMyMembershipRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemberResponseDto"];
				};
			};
		};
	};
	MemberController_getById_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemberResponseDto"];
				};
			};
		};
	};
	MemberController_delete_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeleteResponseDto"];
				};
			};
		};
	};
	MemberController_update_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateMemberRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemberResponseDto"];
				};
			};
		};
	};
	MemberController_mergePreview_v1: {
		parameters: {
			query: {
				dropId: string;
			};
			header?: never;
			path: {
				/** @description Keep member id (the surviving member) */
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MergeMembersPreviewResponseDto"];
				};
			};
		};
	};
	MemberController_merge_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Keep member id (the surviving member) */
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["MergeMembersRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MergeMembersResponseDto"];
				};
			};
		};
	};
	CampaignController_list_v1: {
		parameters: {
			query?: {
				status?: "DRAFT" | "ACTIVE" | "COMPLETED" | "CANCELLED";
				offset?: number;
				limit?: number;
			};
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CampaignListResponseDto"];
				};
			};
		};
	};
	CampaignController_create_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateCampaignRequestDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CampaignResponseDto"];
				};
			};
		};
	};
	CampaignController_getById_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CampaignWithItemsResponseDto"];
				};
			};
		};
	};
	CampaignController_delete_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeleteResponseDto"];
				};
			};
		};
	};
	CampaignController_update_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateCampaignRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CampaignResponseDto"];
				};
			};
		};
	};
	CampaignController_progress_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CampaignProgressResponseDto"];
				};
			};
		};
	};
	CampaignController_restore_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CampaignResponseDto"];
				};
			};
		};
	};
	CampaignController_addItem_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateCampaignItemRequestDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CampaignItemResponseDto"];
				};
			};
		};
	};
	CampaignController_deleteItem_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				itemId: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeleteResponseDto"];
				};
			};
		};
	};
	CampaignController_updateItem_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				itemId: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateCampaignItemRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CampaignItemResponseDto"];
				};
			};
		};
	};
	PledgeController_list_v1: {
		parameters: {
			query?: {
				campaignId?: string;
				campaignItemId?: string;
				memberId?: string;
				status?: "ACTIVE" | "FULFILLED" | "CANCELLED";
				offset?: number;
				limit?: number;
			};
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PledgeListResponseDto"];
				};
			};
		};
	};
	PledgeController_create_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreatePledgeRequestDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PledgeResponseDto"];
				};
			};
		};
	};
	PledgeController_getById_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PledgeResponseDto"];
				};
			};
		};
	};
	PledgeController_delete_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeleteResponseDto"];
				};
			};
		};
	};
	PledgeController_update_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdatePledgeRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PledgeResponseDto"];
				};
			};
		};
	};
	TransactionController_list_v1: {
		parameters: {
			query?: {
				memberId?: string;
				campaignId?: string;
				campaignItemId?: string;
				pledgeId?: string;
				type?:
					| "TITHE"
					| "OFFERING"
					| "MISSION_GIVING"
					| "FIRST_FRUIT"
					| "COMMITMENT"
					| "DONATION"
					| "OTHER";
				dateFrom?: string;
				dateTo?: string;
				offset?: number;
				limit?: number;
			};
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TransactionListResponseDto"];
				};
			};
		};
	};
	TransactionController_create_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateTransactionRequestDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TransactionResponseDto"];
				};
			};
		};
	};
	TransactionController_summary_v1: {
		parameters: {
			query: {
				months: string;
			};
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TransactionSummaryResponseDto"];
				};
			};
		};
	};
	TransactionController_getById_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TransactionResponseDto"];
				};
			};
		};
	};
	TransactionController_delete_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeleteResponseDto"];
				};
			};
		};
	};
	TransactionController_update_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateTransactionRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TransactionResponseDto"];
				};
			};
		};
	};
	InvitationController_list_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["InvitationListResponseDto"];
				};
			};
		};
	};
	InvitationController_issue_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["IssueInvitationRequestDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["InvitationResponseDto"];
				};
			};
		};
	};
	InvitationController_lookup_v1: {
		parameters: {
			query: {
				token: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LookupInvitationResponseDto"];
				};
			};
		};
	};
	InvitationController_accept_v1: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AcceptInvitationRequestDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["InvitationResponseDto"];
				};
			};
		};
	};
	InvitationController_cancel_v1: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Invitation UUID */
				invitationId: string;
				/** @description Tenant UUID or slug */
				tenantId: unknown;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["InvitationResponseDto"];
				};
			};
		};
	};
}
